Linear Algebra Notes

Textbook: Linear Algebra and Its Applications 5th Edition (David C. Lay,
Steven R. Lay, & Judi J. McDonald)

* Chapter 1 - Linear Equations
** System of Linear Equations
*** What is a Linear Equation?
With variables x_{1}, x_{2}, ..., x_{n} is an equation in the form:
a_{1}x_{1} + a_{2}x_{2} + ... + a_{n}x_{n} = b and =coefficients= a_{1}, a_{2}, ..., a_{n} are real or complex numbers

*** System of Linear Equations (Linear System)
A system of linear equations are one or more linear equations that deal with the
same variables x_{1}, ..., x_{n}

An example of how one might look like:
2x_{1} + 3x_{2} + 1.4x_{3} = 8
x_{1}       -   3x_{3} = -7

*** Solution Format (*not* how to solve them)
The solution to a system of linear equations is a list (s_{1}, s_{2}, ..., s_{n}) that
make _each_ equation true when the solution values s_{1}, s_{2}, ..., s_{n} are substituted
for x_{1}, x_{2}, ..., x_{n}, respectively.

*** Some Properties of Linear Systems
The set of all possible solutions is called the =solution set= of the linear system.

Two linear systems are said to be =equivalent= if they have the same solution set.

A System of Linear Equations has:
1. No solution, or
2. Exactly one solution, or
3. Infinitely many solutions

A linear system is =inconsistent= if no solutions and =consistent= if one or infinitely many.

** Matrix Notation
We can represent the important information of a linear system in a form called a
=matrix=.

Consider the following linear system:

    x_{1} - 2x_{2} +  x_{3} = 0
         2x_{2} - 8x_{3} = 8
    5x_{1}      - 5x_{3} = 10

Align the =coefficients= of each variable in columns, we create the following
=coefficient matrix=:

    \begin{bmatrix}
    1 & -2 & 1\\
    0 & 2 & -8\\
    5 & 0 & -5
    \end{bmatrix}

If we add the values of the right-hand side of the linear systems, we have the
=augmented matrix= of the system:

    \begin{bmatrix}
    1 & -2 & 1 & 0\\
    0 & 2 & -8 & 8\\
    5 & 0 & -5 & 10
    \end{bmatrix}

*** Size of Matrix
Just tells us how many rows and columns there are in a matrix

The coefficient matrix above has 3 rows and 3 columns and is called a 3x3 (read
"3 by 3") matrix.

The augmented matrix above has 3 rows and 4 columns, a 3x4 matrix

*Number of rows always comes first*

** Solving a Linear System
Solving a linear system is pretty easy. The basic idea is to take the x_{1} term of
one linear equation and eliminate the x_{1} terms from the other linear equations.
You do the same with x_{2} and so on. In matrix form use an _augmented matrix_.

*** Elementary Row Operations
There are three row operations that can be used to help with the algorithm
discussed above. These operations work because they don't change the solution
set.

**** (=Replacement=) Replace one row by the sum of itself and a multiple of another row

Example:

    \begin{bmatrix}
    1 & -2 & 1\\\
    0 & 2 & -8\\\
    5 & 0 & -5
    \end{bmatrix}

Add a multiple of -5 of row 1 to row 3

row 1 * -5: [-5 10 -5]
row 3 + (row 1 * -5): [-5 10 -5] + [5 0 -5] = [0 10 -10]

The matrix becomes

    \begin{bmatrix}
    1 & -2 & 1\\
    0 & 2 & -8\\
    0 & 10 & -10
    \end{bmatrix}

**** (=Interchange=) Interchange two rows

\begin{bmatrix}
1 & -2 & 1\\
0 & 2 & -8\\
5 & 0 & -5
\end{bmatrix}

Interchange row 1 and row 3
The matrix becomes

\begin{bmatrix}
5 & 0 & -5\\
0 & 2 & -8\\
1 & -2 & 1
\end{bmatrix}

**** (=Scaling=) Multiply all entries in a row by a non-zero constant

\begin{bmatrix}
1 & -2 & 1\\
0 & 2 & -8\\
5 & 0 & -5
\end{bmatrix}

Scale row 1 by 4
The matrix becomes

\begin{bmatrix}
4 & -8 & 4\\
0 & 2 & -8\\
5 & 0 & -5
\end{bmatrix}

*** Example of Solving a Linear System
The Linear System to Solve

    x_{1} - 2x_{2} +  x_{3} = 0
         2x_{2} - 8x_{3} = 8
    5x_{1}      - 5x_{3} = 10

Augmented Matrix Form

\begin{bmatrix}
1 & -2 & 1 & 0\\
0 & 2 & -8 & 8\\
5 & 0 & -5 & 10
\end{bmatrix}

=Scale= row 1 by 5

\begin{bmatrix}
5 & -10 & 5 & 0\\
0 & 2 & -8 & 8\\
5 & 0 & -5 & 10
\end{bmatrix}

Add (-1 * row 1) to row 3 (=replacement=)

\begin{bmatrix}
5 & -10 & 5 & 0\\
0 & 2 & -8 & 8\\
0 & 10 & -10 & 10
\end{bmatrix}

Add (5 * row 2) to row 1 (=replacement=)
Add (-5 * row 2) to row 3 (=replacement=)

\begin{bmatrix}
5 & 0 & -35 & 40\\
0 & 2 & -8 & 8\\
0 & 0 & 30 & -30
\end{bmatrix}

=Scale= row 1 by 1/5
=Scale= row 2 by 1/2
=Scale= row 3 by 1/30

\begin{bmatrix}
1 & 0 & -7 & 8\\
0 & 1 & -4 & 4\\
0 & 0 & 1 & -1
\end{bmatrix}

Add (7 * row 3) to row 1 (=replacement=)
Add (4 * row 3) to row 2 (=replacement=)

\begin{bmatrix}
1 & 0 & 0 & 1\\
0 & 1 & 0 & 0\\
0 & 0 & 1 & -1
\end{bmatrix}

We have found the solution set /(1, 0, -1)/. Let's switch back from matrix form to
see another perspective.

x_{1}       = 1
   x_{2}    = 0
      x_{3} = -1



Let's verify by plugging in the solution set in the original linear system

    x_{1} - 2x_{2} +  x_{3} = 0
         2x_{2} - 8x_{3} = 8
    5x_{1}      - 5x_{3} = 10

Remember the solution set is (1, 0, -1), so x_{1} = 1, x_{2} = 0, and x_{3} = -1. We
plug in

    (1) - 2(0) +  (-1) = 0
          2(0) - 8(-1) = 8
    5(1)       - 5(-1) = 10

Simplify

                     0 = 0
                     8 = 8
                    10 = 10

LHS and RHS agree, so this solution is valid

/This is an only solution, we'll see how infinitely many and no solutions look like later/

** Existence and Uniqueness of Solution Set
*** Two Fundamental Questions of a Linear System
1. Is the system *consistent*; that is, at least one solution exist?
2. If solution exists, is it the only one; that is, is the solution unique?

*** How To Check If Linear System is Consistent?
One way to check for consistency is to put the augmented matrix in a triangular form.
Something like this

\begin{bmatrix}
1 & * & * & * \\
0 & 3 & * & * \\
0 & 0 & 4 & * \\
0 & 0 & 0 & 7
\end{bmatrix}

*We will learn more about this form later*

When we have this form we can easily check if it will be solvable or for stuff
that doesn't make sense (in the example above the last row in equation form says
0 = 7), in that case no solution exists and it's inconsistent.

** Row Reduction and Echelon Forms
*** Echelon Form (Row Echelon Form) & Reduced Echelon Form (Reduced Row Echelon Form)
A _rectangular_ matrix is in =Echelon Form= if it has these three properties

1. All nonzero rows are above any rows of all zeros
2. Each leading entry of a row is in a column to the right of the leading entry
   of the row above it
3. All entries in a column below a leading entry are zeros

The matrix is in =Reduced Echelon Form= if it also has these additional properties

4. The leading entry in each nonzero row is 1
5. Each leading 1 is the only nonzero entry in its column


Echelon Form Examples
    x is any nonzero value
    \diamond is any value including zero

\begin{bmatrix}
x & \diamond & \diamond & \diamond \\
0 & x & \diamond & \diamond \\
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0
\end{bmatrix}

\begin{bmatrix}
x & \diamond & \diamond & \diamond & \diamond & \diamond \\
0 & x & \diamond & \diamond & \diamond & \diamond \\
0 & 0 & 0 & x & \diamond & \diamond \\
0 & 0 & 0 & 0 & x & \diamond \\
0 & 0 & 0 & 0 & 0 & x \\
\end{bmatrix}

Reduced Echelon Form
    x is any nonzero value
    \diamond is any value including zero

\begin{bmatrix}
1 & 0 & \diamond & \diamond \\
0 & 1 & \diamond & \diamond \\
0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0
\end{bmatrix}

\begin{bmatrix}
1 & 0 & \diamond & 0 & 0 & \diamond \\
0 & 1 & \diamond & 0 & 0 & \diamond \\
0 & 0 & 0 & 1 & 0 & \diamond \\
0 & 0 & 0 & 0 & 1 & \diamond \\
\end{bmatrix}

*** Row Reduction
Any nonzero matrix can be =row reduced= to an echelon form using any of the
elementary row operations

We find that the Reduced Echelon Form we get from row reducing a matrix is
unique, the following theorem follows

=Theorem 1: Uniqueness of the Reduced Echelon Form=
    =Each matrix is row equivalent to one and only one reduced echelon matrix=

*** Pivot Positions
A =pivot position= in a Matrix /A/ is a location in /A/ that corresponds to a leading
1 in a reduced echelon form. A =pivot column= is a column that contains the pivot
position.

*** Row Reduction Algorithm
A four step algorithm to put a matrix into echelon form. After the four steps a
fifth step can be made to put into reduced echelon form.

    Step 1: Begin with the left-most nonzero column. This is the pivot column. The
    pivot position is at top.

    Step 2: Select a nonzero entry in the pivot column as a pivot. If necessary,
    interchange rows to move this entry into the pivot position.

    Step 3: Use row replacement operations to create zeros in all positions below
    the pivot

    Step 4: Ignore the row(s) with the current pivot position and above. Repeat
    steps 1-3 until no more nonzero rows to modify.

Extra step to put into reduced echelon form

    Step 5: Working from the rightmost pivot to upwards and left, create zeros
    above each pivot and scale the pivot to be one using elementary row operations.

*** Checking Existence and Uniqueness (continued...)
Putting the matrix in echelon form is the perfect tool to check the existence
and uniqueness of a linear system.

Example

The following matrix is in echelon form

\begin{bmatrix}
3 & -9 & 12 & -9 & 6 & 15\\
0 & 2 & -4 & 4 & 2 & -6\\
0 & 0 & 0 & 0 & 1 & 4
\end{bmatrix}

/Since we don't see untrue statements like /1 = 0/, we can say that a solution
exists.

From looking at which columns are pivot columns, we know that x_{1}, x_{2}, & x_{5} are
our =basic variables= and x_{3} & x_{4} are our =free variables=.

Since we have free variables we can immediately say that their are infinitely
many solutions.

We have the following theorem

=Theorem 2: Existence and Uniqueness Theorem=
    =A linear system is consistent if and only if the rightmost column of the=
    =augmented matrix is not a pivot column—that is, if and only if an echelon form=
    =of the augmented matrix has no row of the form=

        =[0 ... 0 b]     with b nonzero=

    =If a linear system is consistent, then the solution set contains either=
      =(i) a unique solution, when there are no free variables, or=
      =(ii) infinitely many solutions, when there is at least one free variable.=
